### ISSUE TITLE
Gerätenamen in der App anzeigen

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/Scrub#5]
@januschke-itestra aktuell wird nur Calliope mini in der App-Suche angezeigt. Es müsste aber auch noch der Gerätename  [XXXXX] hinzugefügt werden, da es ansonsten in Klassen sehr kompliziert wird den richtigen Calliope mini zu finden. ;)
![IMG_0334](https://github.com/calliope-edu/Scrub/assets/14014852/791a117e-8dcc-43bc-bd66-13bcccd6d916)

**Comment by januschke-itestra** [comment]
@joernalraun der Name des Gerätes wird nicht von der App vorgegeben. Es wird der empfangene Name der gefundenen Bluetooth Geräte angezeigt. Das scheint durch die Bluetooth Verbindung selbst oder den Calliope mini vorgegeben zu sein.
Ich habe meinen calliope komplett vergessen lassen und dann erneut gesucht, dann wurde mir der Gerätename komplett angezeigt. Also hier ist keine Änderung in der App nötig (und das fehlen könnten wir auf den Weg auch nicht korrigieren, da die Informationen fehlen).
![Bildschirmfoto 2024-05-23 um 10 17 05](https://github.com/calliope-edu/Scrub/assets/148525450/7941ed3f-38db-4233-b3e9-9962986e74d1)

**Comment by joernalraun** [comment]
Alles klar!
